### PR TITLE
Interface layout tweaks

### PR DESCRIPTION
**Pull request by zhguyu**
The target of this work is to make the UI look more polished under the new font. Most of the work is to slightly adjust the hardcoded positions of UI elements. So most of the changes should be pretty subtle, but somehow they make the UI look more completed.
I will look into padding / pixel offset issues later and see if offsets or tabs would be better.

### CODE REVIEW

**Comment by zhguyu** [comment]
The build test still fails so I really have no idea what's wrong. Probably not in the commits I made.

**Comment by Ruin0x11** [comment]
I think it looks pretty good so far.

It might be unrelated since it's been an issue for a while, but the list highlighting is pretty off right now. The selection highlight and cursor aren't in the right place. Also in the skills list the text clips into the key indicator:

2024-01-13 21_21_02-OpenNefia

In Elona+:

2024-01-13 21_19_46-Elona+ Custom-GX 2 14 1 0


Maybe this could be fixed while you're at it? Or I can merge when you're ready.

**Comment by zhguyu** [comment]
In my opinion, the root cause of the two problems you mentioned: the selection highlight having an incorrect width, and the text clipping into the keyname indicator, has been the fact that the SetPosition() method in UiElement class not _entirely_ decoupled from UIScale, which is counter-intuitive because a developer (or user) shouldn't need to worry about the UI scale when making UI layouts. It should be safe for them to presume that the position vectors are always in effective pixels under 1.0 scaling, and when the scaling changes in-game the rendering engine should properly handles the scaling of positions, asset sizes and font sizes. As far as I know this is the case for web development.

The SetSize() and SetPosition() are _mostly_ decoupled from UIScale in practice, but it's ultimately up to the developer to decide.

I just push a commit to fix the issues you mentioned. It's basically replacing all UIScale-aware sizes with non-aware ones.

**Comment by zhguyu** [comment]
In my opinion, the root cause of the two problems you mentioned: the selection highlight having an incorrect width, and the text clipping into the keyname indicator, has been the fact that the SetPosition() method in UiElement class not _entirely_ decoupled from UIScale, which is counter-intuitive because a developer (or user) shouldn't need to worry about the UI scale when making UI layouts. It should be safe for them to presume that the position vectors are always in effective pixels under 1.0 scaling, and when the scaling changes in-game the rendering engine should properly handles the scaling of positions, asset sizes and font sizes. As far as I know this is the case for web development.

The SetSize() and SetPosition() are _mostly_ decoupled from UIScale in practice, but it's ultimately up to the developer to decide.

I just push a commit to fix the issues you mentioned. It's basically replacing all UIScale-aware sizes with non-aware ones.
屏幕截图 2024-01-14 095219

**Comment by zhguyu** [comment]
There is probably a race condition between `UiPagedContainer.HandleKeyBindDown()` and `UiPagedList.HandleKeyBindDown()`. I discovered this when I removed the hardcoded width in `SkillsListControl.GetPreferredSize()` (which results in the UiPagedList becoming much shorter in width), after which when the chara info page is opened and switched to the skills list page and when the mouse is on the page, pressing the `Up` and `Down` arrow key wouldn't result in any response (they should switch between the cells in the list) whereas pressing `Left` or `Right` would response normally. This is the behaviour of `UiPagedContainer.HandleKeyBindDown()` instead of `UiPagedList.HandleKeyBindDown()` because the former doesn't handle `Up` and `Down` keys.

On the other hand, if `Up` and `Down` key works normally, then it probably indicates that it is the latter handler that is triggered, which can be dangerous - in this case `CurrentPage` in `UiPagedContainer` may not be properly updated. Maybe it's not a good idea to put a paged element inside another paged element after all.

**Comment by zhguyu** [comment]
There is probably a race condition between `UiPagedContainer.HandleKeyBindDown()` and `UiPagedList.HandleKeyBindDown()`. I discovered this when I removed the hardcoded width in `SkillsListControl.GetPreferredSize()` (which results in `UiPagedList` becoming much shorter in width), after which when the chara info page is opened and switched to the skills list page and when the mouse is on the page, pressing the `Up` and `Down` arrow key wouldn't result in any response (they should switch between the cells in the list) whereas pressing `Left` or `Right` would response normally. This is the behaviour of `UiPagedContainer.HandleKeyBindDown()` instead of `UiPagedList.HandleKeyBindDown()` because the former doesn't handle `Up` and `Down` keys.

On the other hand, if `Up` and `Down` key works normally, then it probably indicates that it is the latter handler that is triggered, which can be dangerous - in this case `CurrentPage` in `UiPagedContainer` may not be properly updated. Maybe it's not a good idea to put a paged element inside another paged element after all.

Although the said change has been discarded and is not in this PR, you can still replicate this behaviour if you put the mouse close enough to the edge of the window (out of the region of the `UiPagedList`), like in the red rectangle in the image below.
test

**Comment by Ruin0x11** [comment]
> It should be safe for them to presume that the position vectors are always in effective pixels under 1.0 scaling, and when the scaling changes in-game the rendering engine should properly handles the scaling of positions, asset sizes and font sizes.

Yeah, thanks for digging into this. This is a limitation of the rendering engine I'm using; it wasn't designed for high-DPI displays at the time I started the project. L﻿ÖVE 12 has better support for this now but I haven't been able to update its C# binding yet. For the time being I had to use a lot of hacks like `GraphicsS` to bolt on scaling support to the engine.

Another issue is that tile scaling is now supported, so there are two separate scaling factors for tiles and the UI. I'm not entirely sure if this usecase is supported by the latest L﻿ÖVE. I think if their high DPI support were used the tiles would always be scaled by the factor of the UI, so both approaches have tradeoffs.

The UI parts are really hobbled together and there are still a lot of issues to resolve. It's a lot of work (though necessary complexity) so I've diverted my attention elsewhere. At some point it will need a major overhaul doing things like unifying `UiElement` and `WispControl`.

> There is probably a race condition between `UiPagedContainer.HandleKeyBindDown()` and `UiPagedList.HandleKeyBindDown()`.

That's probably one of the UI bugs I was trying to hunt down but hadn't solved yet. The UI system was originally designed as a mouse-first interface so I think the element focus can be accidentally stolen by something depending on mouse position or other engine state. At that point the keybindings can work inconsistently.

Specifically, what I think happened in the first case was `UiPagedContainer` unintentionally became the "targeted" element for key commands. That doesn't handle `Up` and `Down` so nothing happened when you pressed them. In reality it should have been the `UiPagedList` contained by `UiPagedContainer` which does handle those events.

If a child element gains key control it passes up any unhandled key commands to its parent and so on, depending on the value of the `UiElement.EventFilter` flag. If `Stop` it won't pass anything upwards, if `Pass` it may do so if the event isn't handled by something else.

To fix this I usually set `EventFilter` to `Pass` and, if there's some child element that should take keyboard focus, override `GrabFocus()` and call `GrabFocus()` on the child.

All this is pretty complicated and hard to reason about. It's partially why I wanted a declarative UI system to make element focus clearer and fix having to manually call `Update()`, `Draw()` and such everywhere. But that's a lot of work. I was planning on working on it when I had all the original UI ported over first.

**Comment by zhguyu** [comment]
I see. Surely UI isn't the outstanding issue at the moment, so it's better to keep it as-is so long as no major bugs are found.

I have no further commits for this PR, please review.

**Comment by Ruin0x11** [comment]
I think it looks good since it's just a few minor offset adjustments so I'll merge. I can take a look at the tests right now since I fixed the one that's failing in my branch. Thanks for the help. I'll create a `develop` branch shortly.

**Pull request merged**
