### PR TITLE
Change font to Dream Han Sans

### PR DESCRIPTION
**Pull request by zhguyu**
The most "clean" way I can find to compensate for the height difference at the moment is to adjust the effective height and line height manually by making the two edits in the code. Fortunately, these hard-coded values can be replaced with constants if necessary. That would be very likely to happen if you want to support more fonts in the future because the height of CJK fonts are a bit of a mess with no clear standard.

### CODE REVIEW

**Comment by zhguyu** [comment]
By the way, Dream Han Sans is derived from Source Han Sans with fixes and improvements, most notably more reasonable line height and better rendering at low dpi.
https://github.com/Pal3love/dream-han-cjk

**Comment by zhguyu** [comment]
Padding doesn't work well with non-monospaced fonts. They should be changed to either pixel offsets or tabs. But that's beyond the scope of this.

**Comment by Ruin0x11** [comment]
Elona's original UI is designed for monospaced fonts, however I architected the UI system so that in the future you could replace the old UI with a different implementation. For example, you could introduce a layout engine, which would be more receptive to non-monospaced fonts (and a prototype of such an engine is included in the code).

One minor thing is the license for the new font (SIL) should also be included in the fonts directory, just so it's clear the usage terms are being followed.

**Comment by Ruin0x11** [comment]
Also I believe those line height constants could be replaced with a config value. If you take a look at `ConfigMenuItem.yml` and `CVars.cs` you can get a rough idea of how the config system is implemented. It's not ideal currently (I think I want everything to be YAML in the future) but it should allow you to insert a "Font Line Height" option in the config menu, probably under the graphics subsection.

**Comment by zhguyu** [comment]
I see. I will look into that. By the way, can you make a new branch so I don't need to pull to `master`? This will make future works on this topic easier. :)

**Comment by Ruin0x11** [comment]
Oh you mean a `develop` branch? I hadn't thought about that actually, I think it's a good idea. What sort of branch setup did you have in mind?

**Comment by zhguyu** [comment]
As you can see the code I pushed barely changes the font and if it is merged to `master` it'll be too destructive and you will need to use it for future development. So it's a good idea to have a `develop` branch so I can merge into that; and we can merge that back to master after I add a entry to the config menu to hotswap font at runtime, if that is appropriate.

**Comment by Ruin0x11** [comment]
That's fine with me, I was treating `master` as my development branch since I've been the sole developer for a long time and it was more convenient to merge directly. Plus I don't have a release schedule since it's still too alpha to progress through the main storyline yet. I can create the `develop` branch after I've got this merged.

**Comment by zhguyu** [comment]
No problem. I've add the license and I'll look into the line height issue a bit later when I have time.

**Comment by zhguyu** [comment]
I've added the config menu entry for adjusting the font height scaling factor. All text elements will redraw as the value changes with one exception: the log at the bottom of the screen wouldn't update until another update is triggered, e.g. the PC moves by a tile. But that would make things a little bit more complex so I think this is good enough.
Please review.

**Comment by Ruin0x11** [comment]
Excellent, thank you for contributing. I'll get around to this when I can.

**Comment by Ruin0x11** [comment]
Sorry to bother, would you mind rebasing onto latest `master`? There was a change to use .NET 8 as the runtime and it seems to be messing up my VS installation.

**Comment by zhguyu** [comment]
Sure. It’s rebased now.

**Comment by Ruin0x11** [comment]
I think it looks pretty nice. Parts of the UI look a bit like Elin now. The one issue I found was in the character sheet where those were padded with spaces instead of pixel offsets. I think those can be worked out later.

Let me know if there's other changes you need to support Chinese. Thank you for helping so far.

**Pull request merged**
